f1 = float(input("enter first float: "))
f2 = float(input("enter second float: "))
print("sum = ", f1+f2)
print("diff = ", f2-f1)
print("square = ", f2**2)
i1 = int(input("enter first int: "))
i2 = int(input("enter second int: "))
print("sum = ", i1+i2)
print("prod = ", i1*i2)
print("DIV = ", i1/i2)
print("INT DIV = ", i1//i2)
print("remainder = ", i1%i2)
print("pow = ", i1**i2)

